### ISSUE TITLE
401 Unauthorized error

### ISSUE THREAD

**Issue by vinayakmali84** [lfalck/AzureRestApiPostmanCollections#1]
I am getting below error while sending message to subscription
<Code>401</Code>
    <Detail>MalformedToken: Failed to parse simple web token. TrackingId:5ba27fd0-a0a5-4929-971a-00571b31c0c7_G4, SystemTracker:devsb.servicebus.windows.net:esignaturerequest-dev-in/messages, Timestamp:2019-08-26T12:24:36</Detail>

I've set enviornment variables as below
pm.environment.set("servicebusNamespace", "devsb");
pm.environment.set("sasKeyName", "RootManageSharedAccessKey");
pm.environment.set("sasKey", "ActualKey");

**Comment by lfalck** [comment]
Are you setting the environment variables in a pre-request script on the Request? That won't work since the collection script which uses the variables is evaluated before the request script.

You should enter them either here: 
![image](https://user-images.githubusercontent.com/30367604/63691213-e646ae80-c80e-11e9-98ce-77d66f6f0eec.png)


Or here if you want to use environment variables: 
![image](https://user-images.githubusercontent.com/30367604/63691147-beefe180-c80e-11e9-9d8d-3c6f7520b8d8.png)

**Comment by vinayakmali84** [comment]
Sorry, I was setting up postman environment variables manually through Pre-Request Scripts option. I will try this. 
Thanks in Advance.

**Comment by vinayakmali84** [comment]
Even after setting up variables I am getting below response
![image](https://user-images.githubusercontent.com/42812720/64007753-5c5e5480-cb32-11e9-9152-0a54d365d254.png)

I've setup variable as below
![image](https://user-images.githubusercontent.com/42812720/64007865-90d21080-cb32-11e9-9b31-a61acc68bfd5.png)

What might be the issue?

**Comment by lfalck** [comment]
You need to change Current Value too.

**Comment by vinayakmali84** [comment]
Thanks a lot. It worked after changing current value.

**Comment by saidbeebay** [comment]
Hello,
I'm facing the same issue. Any chance to share the collection or at least the script generating the SAS Token? :-)
Thanks a lot.

**Comment by lfalck** [comment]
@saidbeebay Have you filled out all the variables with both intial value and current value?

Both the collection and the script are in the repo.
